apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bjw-s.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      values: |
        controllers:
          prowlarr:
            containers:
              app:
                image:
                  repository: ghcr.io/onedr0p/prowlarr-develop
                  tag: 1.25.4.4818@sha256:6c913ad625bb74468b0ffacd8ca6ed99c4d18701e22b6e5a3b0e4e9bc525b1c6
                env:
                  TZ: America/New_York
                  PROWLARR__INSTANCE_NAME: Prowlarr
                  PROWLARR__PORT: &port 9696
                  PROWLARR__APPLICATION_URL: "https://prowlarr.local.example.com"
                  PROWLARR__LOG_LEVEL: info
                  PROWLARR__API_KEY: "your-api-key-here"
                resources:
                  requests:
                    cpu: 10m
                    memory: 100Mi
                  limits:
                    memory: 500Mi
        service:
          app:
            controller: prowlarr
            ports:
              http:
                port: *port
        ingress:
          app:
            enabled: true
            className: nginx
            hosts:
              - host: prowlarr.local.example.com
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
        persistence:
          config:
            enabled: true
            type: hostPath
            hostPath: /opt/prowlarr/config
            hostPathType: DirectoryOrCreate
            globalMounts:
              - path: /config  destination:
    server: https://kubernetes.default.svc
    namespace: arr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
