apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      values: |
        controllers:
          prowlarr:
            containers:
              app:                
                image:
                  repository: ghcr.io/onedr0p/prowlarr-develop
                  tag: 1.26.2.4886
                env:
                  TZ: America/New_York
                  PROWLARR__INSTANCE_NAME: Prowlarr
                  PROWLARR__PORT: &port 9696
                  PROWLARR__APPLICATION_URL: "https://prowlarr.michaelwilkes.dev"
                  PROWLARR__LOG_LEVEL: info
                  PROWLARR__API_KEY: "your-api-key-here"
                resources:
                  requests:
                    cpu: 10m
                    memory: 100Mi
                  limits:
                    memory: 500Mi
        service:
          app:
            controller: prowlarr
            ports:
              http:
                port: *port        
        ingress:
          app:
            enabled: true
            className: nginx            
            annotations:
              cert-manager.io/cluster-issuer: selfsigned-issuer
            hosts:
              - host: prowlarr.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: prowlarr-tls
                hosts:
                  - prowlarr.michaelwilkes.dev        
        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-rbd
            size: 1Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /config
  destination:
    server: https://kubernetes.default.svc
    namespace: arr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
