# Radarr Secrets managed by Infisical
# 
# PREREQUISITE: Add the API key to Infisical under /radarr path in the ombra-mi-wk project

apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: radarr-infisical-secret
  namespace: arr
spec:
  resyncInterval: 60
  managedSecretReference:
    secretName: radarr-secrets
    secretNamespace: arr
    secretType: Opaque
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/radarr"
