apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      values: |
        controllers:
          radarr:
            containers:              
              app:                
                image:
                  repository: ghcr.io/home-operations/radarr
                  tag: 5.27.0.10101
                env:
                  TZ: America/New_York
                  PUID: 1000
                  PGID: 1000
                resources:
                  requests:
                    cpu: 10m
                    memory: 250Mi
                  limits:
                    memory: 2Gi
        service:
          app:
            controller: radarr
            ports:
              http:
                port: *port        
        ingress:
          app:
            enabled: true
            className: nginx            
            annotations:
              cert-manager.io/cluster-issuer: selfsigned-issuer
            hosts:
              - host: radarr.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: radarr-tls
                hosts:
                  - radarr.michaelwilkes.dev        
        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-rbd
            size: 1Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /config
          downloads:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-rbd
            size: 100Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /downloads
          media:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-cephfs
            size: 1Ti
            accessMode: ReadWriteMany
            globalMounts:
              - path: /media
  destination:
    server: https://kubernetes.default.svc
    namespace: arr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
