apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      values: |
        controllers:
          sonarr:
            containers:
              app:
                image:
                  repository: ghcr.io/onedr0p/sonarr-develop
                  tag: 4.0.9.2513@sha256:31c0f7881c18d496a45616bad4b02ab6588b95836615122042c8709d5edb0241
                env:
                  TZ: America/New_York
                  SONARR__INSTANCE_NAME: Sonarr
                  SONARR__PORT: &port 8989
                  SONARR__APPLICATION_URL: "https://sonarr.michaelwilkes.dev"
                  SONARR__LOG_LEVEL: info
                  SONARR__API_KEY: "your-api-key-here"
                resources:
                  requests:
                    cpu: 10m
                    memory: 250Mi
                  limits:
                    memory: 2Gi
        service:
          app:
            controller: sonarr
            ports:
              http:
                port: *port        
        ingress:
          app:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-staging
            hosts:
              - host: sonarr.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: sonarr-tls
                hosts:
                  - sonarr.michaelwilkes.dev
        persistence:
          config:
            enabled: true
            type: hostPath
            hostPath: /opt/sonarr/config
            hostPathType: DirectoryOrCreate
            globalMounts:
              - path: /config
          downloads:
            enabled: true
            type: hostPath
            hostPath: /opt/downloads
            hostPathType: DirectoryOrCreate
            globalMounts:
              - path: /downloads
          media:
            enabled: true
            type: hostPath
            hostPath: /opt/plex/media/tv
            hostPathType: DirectoryOrCreate            
            globalMounts:
              - path: /media
  destination:
    server: https://kubernetes.default.svc
    namespace: arr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
