apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-operator
  namespace: argocd
spec:  
  project: default  
  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    chart: secrets-operator
    targetRevision: 0.10.15
    helm:
      values: |
        # Infisical Secrets Operator configuration
        controllerManager:
          manager:
            image:
              repository: infisical/kubernetes-operator
              tag: v0.10.15
            resources:
              limits:
                cpu: 500m
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 64Mi
        
        # Install CRDs
        installCRDs: true
        
        # Service monitor for Prometheus (if available)
        serviceMonitor:
          enabled: false
        
        # Security context
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 65532
        
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
