apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Deploy Infisical operator only
  # Auth credentials should be applied manually for security
  - infisical-operator.yaml
