apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      values: |
        controllers:
          sabnzbd:
            containers:
              app:
                image:
                  repository: ghcr.io/onedr0p/sabnzbd
                  tag: 4.3.3@sha256:6614d759bbaa6884926c6aa75018339bd35cd1add0ff92c907087327dd470477
                env:
                  TZ: America/New_York                  
                  SABNZBD__PORT: &port 8080
                  SABNZBD__HOST_WHITELIST_ENTRIES: >-
                    sabnzbd,
                    sabnzbd.downloads,
                    sabnzbd.downloads.svc,
                    sabnzbd.downloads.svc.cluster.local,
                    sabnzbd.michaelwilkes.dev
                resources:
                  requests:
                    cpu: 10m
                    memory: 250Mi
                  limits:
                    memory: 8Gi
        service:
          app:
            controller: sabnzbd
            ports:
              http:
                port: *port        
        ingress:
          app:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-staging
            hosts:
              - host: sabnzbd.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: sabnzbd-tls
                hosts:
                  - sabnzbd.michaelwilkes.dev
        persistence:
          config:
            enabled: true
            type: hostPath
            hostPath: /opt/sabnzbd/config
            hostPathType: DirectoryOrCreate
            globalMounts:
              - path: /config
          downloads:
            enabled: true
            type: hostPath
            hostPath: /opt/downloads
            hostPathType: DirectoryOrCreate
            globalMounts:
              - path: /downloads
          incomplete:
            enabled: true
            type: hostPath
            hostPath: /opt/sabnzbd/incomplete
            hostPathType: DirectoryOrCreate
            globalMounts:
              - path: /incomplete-downloads
          media:
            enabled: true
            type: hostPath
            hostPath: /opt/plex/media
            hostPathType: DirectoryOrCreate            
            globalMounts:
              - path: /media
  destination:
    server: https://kubernetes.default.svc
    namespace: downloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
