apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      values: |        
        controllers:
          sabnzbd:
            pod:
              securityContext:
                runAsUser: 2000
                runAsGroup: 2000
                runAsNonRoot: true
                fsGroup: 2000
                fsGroupChangePolicy: OnRootMismatch
            initContainers:
              init-permissions:
                image:
                  repository: busybox
                  tag: latest
                command:
                  - /bin/sh
                  - -c
                  - |
                    chown -R 2000:2000 /config
                    chmod -R 755 /config
                securityContext:
                  runAsUser: 0
                volumeMounts:
                  - name: config
                    mountPath: /config
            containers:
              app:
                image:
                  repository: ghcr.io/home-operations/sabnzbd
                  tag: 4.5.1                env:
                  TZ: America/New_York
                  SABNZBD__APP__INSTANCENAME: SABnzbd
                  SABNZBD__SERVER__PORT: &port 8080
                  SABNZBD__LOG__LEVEL: info
                envFrom:
                  - secretRef:
                      name: sabnzbd-secrets
                probes:
                  liveness: &probes
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /
                        port: *port
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness: *probes
                resources:
                  requests:
                    cpu: 10m
                    memory: 250Mi
                  limits:
                    memory: 8Gi
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL
        service:
          app:
            controller: sabnzbd            
            ports:
              http:
                port: 8080
        ingress:
          app:
            enabled: true
            className: nginx            
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: sabnzbd.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: sabnzbd-tls
                hosts:
                  - sabnzbd.michaelwilkes.dev        
        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-rbd
            size: 1Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /config
          downloads:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-rbd
            size: 100Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /downloads
          incomplete:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-rbd
            size: 50Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /incomplete-downloads
          media:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-cephfs
            size: 1Ti
            accessMode: ReadWriteMany
            globalMounts:
              - path: /media
  destination:
    server: https://kubernetes.default.svc
    namespace: downloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
