apiVersion: batch/v1
kind: Job
metadata:
  name: setup-directories
  namespace: arr
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: setup-directories
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Creating TRaSH-recommended directory structure..."
          mkdir -p /data/movies
          mkdir -p /data/tv
          mkdir -p /data/downloads/complete/movies
          mkdir -p /data/downloads/complete/tv
          mkdir -p /data/downloads/torrents/movies
          mkdir -p /data/downloads/torrents/tv
          chmod -R 775 /data
          echo "Directory structure created successfully!"
          ls -la /data
          ls -la /data/downloads
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:      
      - name: data
        persistentVolumeClaim:
          claimName: shared-media-data
