apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-secrets
  namespace: secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "patch", "list"]
