apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-argocd-secrets
  namespace: argocd
rules:
  # Allow reading all secrets to find the cluster secret
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  # Allow managing the specific cluster-kubeconfig secret
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
    resourceNames: ["cluster-kubeconfig"]
  # Allow managing the cluster-kubeconfig-view configmap
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
    resourceNames: ["cluster-kubeconfig-view"]
