apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: wazuh-authd-pass-secret
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/wazuh/authd"
        recursive: false
  managedSecretReference:
    secretName: wazuh-authd-pass
    secretNamespace: wazuh
    secretType: Opaque
    creationPolicy: Owner