apiVersion: v1
kind: Secret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
type: Opaque
data:
  username: d2F6dWgtd3Vp          # "wazuh-wui"
  password: TXlTM2NyMzdQNDUwci4qLQ==  # "MyS3cr37P450r.*-" (example)
