apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: wazuh-authd-pass-infisical
  namespace: wazuh
spec:
  resyncInterval: 60
  managedSecretReference:
    secretName: wazuh-authd-pass
    secretNamespace: wazuh
    secretType: Opaque
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/wazuh/wazuh-authd-pass"
