# Plex Secrets managed by Infisical
# 
# This manages sensitive Plex configuration like claim tokens
# Store the PLEX_CLAIM token in Infisical under /plex path

apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: plex-infisical-secret
  namespace: plex
spec:
  resyncInterval: 60
  managedSecretReference:
    secretName: claim-token
    secretNamespace: plex
    secretType: Opaque
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/plex"
