apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      values: |
        controllers:
          plex:
            containers:
              app:
                image:
                  repository: ghcr.io/home-operations/plex
                  tag: 1.41.8.9834                
                env:
                  TZ: America/New_York
                  PUID: 1000
                  PGID: 1000
                envFrom:
                  - secretRef:
                      name: claim-token
                resources:
                  requests:
                    cpu: 100m
                    memory: 2Gi
                  limits:
                    memory: 8Gi
        service:
          app:
            controller: plex
            type: LoadBalancer
            loadBalancerIP: 192.168.55.210
            ports:
              http:
                port: 32400        
        ingress:
          app:
            enabled: true
            className: nginx            
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: plex.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: plex-tls
                hosts:
                  - plex.michaelwilkes.dev        
        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-rbd
            size: 10Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /config
          media:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-cephfs
            size: 500Gi
            accessMode: ReadWriteMany
            globalMounts:
              - path: /media
          transcode:
            enabled: true
            type: emptyDir
            globalMounts:
              - path: /transcode
  destination:
    server: https://kubernetes.default.svc
    namespace: plex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
