# Overseerr Secrets managed by Infisical
# 
# PREREQUISITE: Add the API key to Infisical under /overseerr path in the ombra-mi-wk project

apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: overseerr-infisical-secret
  namespace: requests
spec:
  resyncInterval: 60
  managedSecretReference:
    secretName: overseerr-secrets
    secretNamespace: requests
    secretType: Opaque
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/overseerr"
