apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-infisical-secret
  namespace: cert-manager
spec:
  resyncInterval: 60
  managedSecretReference:
    secretName: cloudflare-api-token-secret
    secretNamespace: cert-manager
    secretType: Opaque
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/cert-manager"
