# Cloudflare API Token Secret for cert-manager DNS challenges
# 
# PREREQUISITE: Create a Cloudflare API token with Zone:Read and DNS:Edit permissions
# Then update this secret with your actual token

apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: "YOUR_CLOUDFLARE_API_TOKEN_HERE"
---
# Alternative: If you prefer to use Infisical for the Cloudflare token
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-infisical-secret
  namespace: cert-manager
spec:
  secretsPath: "/cert-manager"
  projectId: "f492c339-2822-40bd-84cb-6f32326a3a38"
  envSlug: "prod"
  secretType: Opaque
  resyncInterval: 60
  managedSecretReference:
    secretName: cloudflare-api-token-secret
    secretNamespace: cert-manager
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      secretsScope:
        projectId: "f492c339-2822-40bd-84cb-6f32326a3a38"
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"        
        secretsPath: "/cert-manager"
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
