apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

commonLabels:
  app.kubernetes.io/part-of: wazuh
  app.kubernetes.io/managed-by: argocd

resources:
  # Storage class for Wazuh PVCs (uses Ceph RBD pool "configs" by default here)
  - storageclass-wazuh.yaml

  # Secrets: credentials and cluster keys (with default demo values; override in your secrets management)
  - secrets/wazuh-api-cred-secret.yaml
  - secrets/wazuh-authd-pass-secret.yaml
  - secrets/wazuh-cluster-key-secret.yaml
  - secrets/dashboard-cred-secret.yaml
  - secrets/indexer-cred-secret.yaml

  # Services and StatefulSets/Deployments from upstream Wazuh
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/wazuh_managers/wazuh-cluster-svc.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/wazuh_managers/wazuh-master-svc.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/wazuh_managers/wazuh-workers-svc.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/wazuh_managers/wazuh-master-sts.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/wazuh_managers/wazuh-worker-sts.yaml

  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/indexer_stack/wazuh-indexer/indexer-svc.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/indexer_stack/wazuh-indexer/cluster/indexer-api-svc.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml

  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/indexer_stack/wazuh-dashboard/dashboard-svc.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml

configMapGenerator:
  - name: indexer-conf
    behavior: create
    files:
      - indexer_conf/opensearch.yml
      - indexer_conf/internal_users.yml
  - name: wazuh-conf
    behavior: create
    files:
      - wazuh_conf/master.conf
      - wazuh_conf/worker.conf
  - name: dashboard-conf
    behavior: create
    files:
      - dashboard_conf/opensearch_dashboards.yml

secretGenerator:
  - name: indexer-certs
    behavior: create
    files:
      - certs/indexer_cluster/root-ca.pem
      - certs/indexer_cluster/node.pem
      - certs/indexer_cluster/node-key.pem
      - certs/indexer_cluster/dashboard.pem
      - certs/indexer_cluster/dashboard-key.pem
      - certs/indexer_cluster/admin.pem
      - certs/indexer_cluster/admin-key.pem
      - certs/indexer_cluster/filebeat.pem
      - certs/indexer_cluster/filebeat-key.pem
  - name: dashboard-certs
    behavior: create
    files:
      - certs/dashboard_http/cert.pem
      - certs/dashboard_http/key.pem
      - certs/indexer_cluster/root-ca.pem

generatorOptions:
  disableNameSuffixHash: true
