apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base
  - ./secrets
  - ./certificates

# Remove upstream single-cert Secret expectations; replace with cert-manager projected volumes
patches:
  - target:
      group: ""
      version: v1
      kind: Secret
      name: indexer-certs
    patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: indexer-certs
      $patch: delete
  - target:
      group: ""
      version: v1
      kind: Secret
      name: dashboard-certs
    patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: dashboard-certs
      $patch: delete

patchesJson6902:
  # Indexer: replace volume[0] (indexer-certs secret) with projected sources
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: wazuh-indexer
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: indexer-certs
          projected:
            sources:
              - secret:
                  name: wazuh-node-tls
                  items:
                    - key: tls.crt
                      path: node.pem
                    - key: tls.key
                      path: node-key.pem
              - secret:
                  name: wazuh-admin-tls
                  items:
                    - key: tls.crt
                      path: admin.pem
                    - key: tls.key
                      path: admin-key.pem
              - secret:
                  name: wazuh-root-ca
                  items:
                    - key: tls.crt
                      path: root-ca.pem
  # Dashboard: volumes[0]=config, volumes[1]=dashboard-certs
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: wazuh-dashboard
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1
        value:
          name: dashboard-certs
          projected:
            sources:
              - secret:
                  name: wazuh-dashboard-tls
                  items:
                    - key: tls.crt
                      path: cert.pem
                    - key: tls.key
                      path: key.pem
              - secret:
                  name: wazuh-root-ca
                  items:
                    - key: tls.crt
                      path: root-ca.pem
  # Manager master: volumes[0]=config, [1]=filebeat-certs, [2]=wazuh-authd-pass
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: wazuh-manager-master
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1
        value:
          name: filebeat-certs
          projected:
            sources:
              - secret:
                  name: wazuh-filebeat-tls
                  items:
                    - key: tls.crt
                      path: filebeat.pem
                    - key: tls.key
                      path: filebeat-key.pem
              - secret:
                  name: wazuh-root-ca
                  items:
                    - key: tls.crt
                      path: root-ca.pem
  # Manager worker: same ordering as master
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: wazuh-manager-worker
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1
        value:
          name: filebeat-certs
          projected:
            sources:
              - secret:
                  name: wazuh-filebeat-tls
                  items:
                    - key: tls.crt
                      path: filebeat.pem
                    - key: tls.key
                      path: filebeat-key.pem
              - secret:
                  name: wazuh-root-ca
                  items:
                    - key: tls.crt
                      path: root-ca.pem
