apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base
  - ./secrets
  - ./certificates

# Remove upstream single-cert Secret expectations; replace with cert-manager projected volumes
patches:
  - target:
      group: ""
      version: v1
      kind: Secret
      name: indexer-certs
    patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: indexer-certs
      $patch: delete
  - target:
      group: ""
      version: v1
      kind: Secret
      name: dashboard-certs
    patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: dashboard-certs
      $patch: delete
  # Patch indexer StatefulSet: project multiple cert secrets into expected filenames
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: wazuh-indexer
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: wazuh-indexer
      spec:
        template:
          spec:
            volumes:
              - name: indexer-certs
                projected:
                  sources:
                    - secret:
                        name: wazuh-node-tls
                        items:
                          - key: tls.crt
                            path: node.pem
                          - key: tls.key
                            path: node-key.pem
                    - secret:
                        name: wazuh-admin-tls
                        items:
                          - key: tls.crt
                            path: admin.pem
                          - key: tls.key
                            path: admin-key.pem
                    - secret:
                        name: wazuh-root-ca
                        items:
                          - key: tls.crt
                            path: root-ca.pem
                secret: null
  # Patch dashboard Deployment: project dashboard tls + root CA
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: wazuh-dashboard
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: wazuh-dashboard
      spec:
        template:
          spec:
            volumes:
              - name: dashboard-certs
                projected:
                  sources:
                    - secret:
                        name: wazuh-dashboard-tls
                        items:
                          - key: tls.crt
                            path: cert.pem
                          - key: tls.key
                            path: key.pem
                    - secret:
                        name: wazuh-root-ca
                        items:
                          - key: tls.crt
                            path: root-ca.pem
                secret: null
  # Patch manager master: project filebeat + root CA
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: wazuh-manager-master
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: wazuh-manager-master
      spec:
        template:
          spec:
            volumes:
              - name: filebeat-certs
                projected:
                  sources:
                    - secret:
                        name: wazuh-filebeat-tls
                        items:
                          - key: tls.crt
                            path: filebeat.pem
                          - key: tls.key
                            path: filebeat-key.pem
                    - secret:
                        name: wazuh-root-ca
                        items:
                          - key: tls.crt
                            path: root-ca.pem
                secret: null
  # Patch manager worker: project filebeat + root CA
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: wazuh-manager-worker
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: wazuh-manager-worker
      spec:
        template:
          spec:
            volumes:
              - name: filebeat-certs
                projected:
                  sources:
                    - secret:
                        name: wazuh-filebeat-tls
                        items:
                          - key: tls.crt
                            path: filebeat.pem
                          - key: tls.key
                            path: filebeat-key.pem
                    - secret:
                        name: wazuh-root-ca
                        items:
                          - key: tls.crt
                            path: root-ca.pem
                secret: null
