apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

resources:
  - namespace.yaml
  # ConfigMaps
  - configmaps/indexer-conf.cm.yaml
  - configmaps/wazuh-conf.cm.yaml
  - configmaps/dashboard-conf.cm.yaml
  # Secrets (managed by Infisical operator)
  - secrets/infisical-indexer-cred.yaml
  - secrets/infisical-dashboard-cred.yaml
  - secrets/infisical-wazuh-api-cred.yaml
  - secrets/infisical-wazuh-authd-pass.yaml
  - secrets/infisical-wazuh-cluster-key.yaml
  - secrets/infisical-indexer-certs.yaml
  - secrets/infisical-dashboard-certs.yaml
  # Services
  - services/wazuh-cluster-svc.yaml
  - services/wazuh-master-svc.yaml
  - services/wazuh-workers-svc.yaml
  - services/indexer-svc.yaml
  - services/indexer-api-svc.yaml
  - services/dashboard-svc.yaml
  # Workloads
  - workloads/wazuh-master-sts.yaml
  - workloads/wazuh-worker-sts.yaml
  - workloads/indexer-sts.yaml
  - workloads/dashboard-deploy.yaml
