apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base
  - ./secrets

# Remove the Secret generators from base; rely on Infisical-provisioned certs
patches:
  - target:
      group: ""
      version: v1
      kind: Secret
      name: indexer-certs
    patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: indexer-certs
      $patch: delete
  - target:
      group: ""
      version: v1
      kind: Secret
      name: dashboard-certs
    patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: dashboard-certs
      $patch: delete
