apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-conf
data:
  master.conf: |
    <ossec_config>
      <global>
        <jsonout_output>yes</jsonout_output>
        <alerts_log>yes</alerts_log>
        <logall>no</logall>
        <logall_json>no</logall_json>
        <email_notification>no</email_notification>
      </global>
      <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>tcp</protocol>
      </remote>
      <indexer>
        <enabled>yes</enabled>
        <hosts>
          <host>https://indexer:9200</host>
        </hosts>
        <ssl>
          <certificate_authorities>
            <ca>/etc/ssl/root-ca.pem</ca>
          </certificate_authorities>
          <certificate>/etc/ssl/filebeat.pem</certificate>
          <key>/etc/ssl/filebeat.key</key>
        </ssl>
      </indexer>
      <cluster>
        <name>wazuh</name>
        <node_name>wazuh-manager-master</node_name>
        <node_type>master</node_type>
        <key>to_be_replaced_by_cluster_key</key>
        <port>1516</port>
        <bind_addr>0.0.0.0</bind_addr>
      </cluster>
    </ossec_config>
  worker.conf: |
    <ossec_config>
      <global>
        <jsonout_output>yes</jsonout_output>
        <alerts_log>yes</alerts_log>
        <logall>no</logall>
        <logall_json>no</logall_json>
        <email_notification>no</email_notification>
      </global>
      <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>tcp</protocol>
      </remote>
      <indexer>
        <enabled>yes</enabled>
        <hosts>
          <host>https://indexer:9200</host>
        </hosts>
        <ssl>
          <certificate_authorities>
            <ca>/etc/ssl/root-ca.pem</ca>
          </certificate_authorities>
          <certificate>/etc/ssl/filebeat.pem</certificate>
          <key>/etc/ssl/filebeat.key</key>
        </ssl>
      </indexer>
      <cluster>
        <name>wazuh</name>
        <node_name>to_be_replaced_by_hostname</node_name>
        <node_type>worker</node_type>
        <key>to_be_replaced_by_cluster_key</key>
        <port>1516</port>
        <bind_addr>0.0.0.0</bind_addr>
        <nodes>
          <node>wazuh-manager-master-0.wazuh-cluster.wazuh</node>
        </nodes>
      </cluster>
    </ossec_config>