apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mhwilkes/ombra-labops.git
    targetRevision: HEAD
    path: gitops/apps/secrets
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: cluster-kubeconfig
    namespace: secrets
    jsonPointers:
    - /data
  - group: ""
    kind: ConfigMap
    name: cluster-kubeconfig-view
    namespace: secrets
    jsonPointers:
    - /data
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-cluster-access
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mhwilkes/ombra-labops.git
    targetRevision: HEAD
    path: gitops/apps/secrets/home-cluster-access
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
