apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-stack
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://github.com/mhwilkes/ombra-labops.git
    targetRevision: HEAD
    path: gitops/apps/workloads/plex
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arr-stack
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://github.com/mhwilkes/ombra-labops.git
    targetRevision: HEAD
    path: gitops/apps/workloads/arr
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: downloads-stack
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://github.com/mhwilkes/ombra-labops.git
    targetRevision: HEAD
    path: gitops/apps/workloads/downloads
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashboard-stack
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://github.com/mhwilkes/ombra-labops.git
    targetRevision: HEAD
    path: gitops/apps/workloads/dashboard
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
