apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-stack
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://github.com/mhwilkes/ombra-labops.git
    targetRevision: HEAD
    path: gitops/apps/workloads/media
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  dependsOn:
  - storage  # Media stack needs shared storage for downloads, media library, and configurations
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashboard-stack
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://github.com/mhwilkes/ombra-labops.git
    targetRevision: HEAD
    path: gitops/apps/workloads/dashboard
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
