apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

labels:
  - pairs:
      app.kubernetes.io/part-of: wazuh
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false

resources:
  - ../../base
  - ../../secrets
  - ./namespace.yaml
  - ./ingress-dashboard.yaml
  - ./ingress-api.yaml

patches:
  # Remove Secret generators from the base so we can use existing Secrets
  - target:
      group: ""
      version: v1
      kind: Secret
      name: indexer-certs
    patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: indexer-certs
      $patch: delete
  - target:
      group: ""
      version: v1
      kind: Secret
      name: dashboard-certs
    patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: dashboard-certs
      $patch: delete

  # Instruct Argo CD to replace resources that otherwise violate immutability (selectors/spec)
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: wazuh-dashboard
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: wazuh-dashboard
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: wazuh-indexer
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: wazuh-indexer
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: wazuh-manager-master
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: wazuh-manager-master
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: wazuh-manager-worker
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: wazuh-manager-worker
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
