apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

labels:
  - pairs:
      app.kubernetes.io/part-of: wazuh
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false

resources:
  - ../../base
  - ./namespace.yaml
  - ./ingress-dashboard.yaml
  - ./ingress-api.yaml

patches:
  # Instruct Argo CD to replace resources that otherwise violate immutability (selectors/spec) and tune resources
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: wazuh-dashboard
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: wazuh-dashboard
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: wazuh-indexer
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: wazuh-indexer
      spec:
        template:
          spec:
            containers:
              - name: wazuh-indexer
                resources:
                  requests:
                    cpu: 500m
                    memory: 2Gi
                  limits:
                    cpu: "2"
                    memory: 4Gi
                env:
                  - name: OPENSEARCH_JAVA_OPTS
                    value: "-Xms2g -Xmx2g -Dlog4j2.formatMsgNoLookups=true"
