apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

commonLabels:
  app.kubernetes.io/part-of: wazuh
  app.kubernetes.io/managed-by: argocd

# Use the base and override behavior for certs to rely on pre-existing Secrets
resources:
  - ../../

# Remove Secret generators from the base so we can use existing Secrets
patches:
  - target:
      group: ""
      version: v1
      kind: Secret
      name: indexer-certs
    patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: indexer-certs
      $patch: delete
  - target:
      group: ""
      version: v1
      kind: Secret
      name: dashboard-certs
    patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: dashboard-certs
      $patch: delete
