apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

labels:
  - pairs:
      app.kubernetes.io/part-of: wazuh
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false

resources:
  - ../../base
  - ./namespace.yaml
  - ./ingress-dashboard.yaml
  - ./ingress-api.yaml
  - ./certificate-dashboard-public.yaml

patches:
  # Instruct Argo CD to replace resources that otherwise violate immutability (selectors/spec) and tune resources
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: wazuh-dashboard
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: wazuh-dashboard
        # Removing Replace=true to avoid full object replacement; strategic merge only.
      spec:
        template:
          spec:
            volumes:
              - name: wazuh-generated-config
                emptyDir: {}
            initContainers:
              - name: generate-wazuh-config
                image: busybox:1.36
                imagePullPolicy: IfNotPresent
                env:
                  - name: WAZUH_API_HOST
                    value: wazuh-indexer
                  - name: API_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: wazuh-api-cred
                        key: username
                  - name: API_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: wazuh-api-cred
                        key: password
                command: ["/bin/sh","-c"]
                args:
                  - >-
                    set -euo pipefail; \
                    echo "[init] generating wazuh.yml"; \
                    cat > /wazuh-generated-config/wazuh.yml <<EOF\n# Autogenerated – do not edit manually.\nhosts:\n  - primary:\n      url: https://${WAZUH_API_HOST}\n      port: 55000\n      username: ${API_USERNAME}\n      password: ${API_PASSWORD}\n      run_as: false\nEOF\n                    chmod 600 /wazuh-generated-config/wazuh.yml; \
                    sed 's/password: .*/password: ********/' /wazuh-generated-config/wazuh.yml; \
                    echo "[init] done";
                volumeMounts:
                  - name: wazuh-generated-config
                    mountPath: /wazuh-generated-config
            containers:
              - name: wazuh-dashboard
                volumeMounts:
                  - name: wazuh-generated-config
                    mountPath: /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
                    subPath: wazuh.yml
                    readOnly: true
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: wazuh-indexer
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: wazuh-indexer
        # Removed Replace=true to avoid immutable field replacement
      spec:
        template:
          spec:
            containers:
              - name: wazuh-indexer
                resources:
                  requests:
                    cpu: 500m
                    memory: 2Gi
                  limits:
                    cpu: "2"
                    memory: 4Gi
                env:
                  - name: OPENSEARCH_JAVA_OPTS
                    value: "-Xms2g -Xmx2g -Dlog4j2.formatMsgNoLookups=true"
