apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

commonLabels:
  app.kubernetes.io/part-of: wazuh
  app.kubernetes.io/managed-by: argocd

resources:
  # Storage class
  - ../../storageclass-wazuh.yaml

  # Credentials and keys via Infisical (no TLS certs here; we rely on existing Secrets)
  - ../../secrets/indexer-cred-infisical.yaml
  - ../../secrets/dashboard-cred-infisical.yaml
  - ../../secrets/wazuh-api-cred-infisical.yaml
  - ../../secrets/wazuh-authd-pass-infisical.yaml
  - ../../secrets/wazuh-cluster-key-infisical.yaml

  # Upstream Wazuh resources
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/wazuh_managers/wazuh-cluster-svc.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/wazuh_managers/wazuh-master-svc.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/wazuh_managers/wazuh-workers-svc.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/wazuh_managers/wazuh-master-sts.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/wazuh_managers/wazuh-worker-sts.yaml

  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/indexer_stack/wazuh-indexer/indexer-svc.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/indexer_stack/wazuh-indexer/cluster/indexer-api-svc.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml

  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/indexer_stack/wazuh-dashboard/dashboard-svc.yaml
  - https://raw.githubusercontent.com/wazuh/wazuh-kubernetes/v4.12.0/wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml

configMapGenerator:
  - name: indexer-conf
    behavior: create
    files:
      - ../../indexer_conf/opensearch.yml
      - ../../indexer_conf/internal_users.yml
  - name: wazuh-conf
    behavior: create
    files:
      - ../../wazuh_conf/master.conf
      - ../../wazuh_conf/worker.conf
  - name: dashboard-conf
    behavior: create
    files:
      - ../../dashboard_conf/opensearch_dashboards.yml

generatorOptions:
  disableNameSuffixHash: true
