apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wazuh-agent
  labels:
    app.kubernetes.io/name: wazuh-agent
    app.kubernetes.io/part-of: wazuh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wazuh-agent
subjects:
  - kind: ServiceAccount
    name: wazuh-agent
    namespace: wazuh
