apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.1.2
    helm:
      values: |
        controllers:
          homeassistant:
            type: deployment
            strategy: Recreate
            pod:
              securityContext:
                runAsUser: 0
                runAsGroup: 0
                runAsNonRoot: false
                fsGroup: 1000
                fsGroupChangePolicy: "Always"
            containers:
              app:
                image:
                  repository: ghcr.io/home-assistant/home-assistant
                  tag: latest
                env:
                  TZ: America/New_York
                probes:
                  liveness:
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /
                        port: 8123
                      initialDelaySeconds: 10
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                  readiness:
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /
                        port: 8123
                      initialDelaySeconds: 10
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                resources:
                  requests:
                    cpu: 50m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 1Gi
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: false
        # persistence is configured at top-level for app-template
        service:
          app:
            controller: homeassistant
            type: ClusterIP
            ports:
              http:
                port: 8123
        ingress:
          app:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
              nginx.ingress.kubernetes.io/compute-full-forwarded-for: "true"
            hosts:
              - host: ha.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: homeassistant-tls
                hosts:
                  - ha.michaelwilkes.dev
        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: home-autx-config
            globalMounts:
              - path: /config
  destination:
    server: https://kubernetes.default.svc
    namespace: home-autx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
