# Infisical-managed secrets for Ceph CSI drivers
# These secrets contain user keys and credentials for accessing the external Ceph cluster

apiVersion: infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ceph-csi-rbd-secret
  namespace: ceph-csi-rbd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  projectId: "{{ .Values.infisical.projectId }}"
  environment: "{{ .Values.infisical.environment }}"
  secretsPath: "/ceph"
  secretName: csi-rbd-secret
  secretType: Opaque
  managedSecretReference:
    secretName: infisical-auth-secret
    secretNamespace: infisical-operator-system
  mapping:
    - secretKey: userID
      infisicalKey: CEPH_RBD_USER_ID
    - secretKey: userKey  
      infisicalKey: CEPH_RBD_USER_KEY
    - secretKey: adminID
      infisicalKey: CEPH_ADMIN_ID
    - secretKey: adminKey
      infisicalKey: CEPH_ADMIN_KEY
---
apiVersion: infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ceph-csi-cephfs-secret
  namespace: ceph-csi-cephfs
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  projectId: "{{ .Values.infisical.projectId }}"
  environment: "{{ .Values.infisical.environment }}"
  secretsPath: "/ceph"
  secretName: csi-cephfs-secret
  secretType: Opaque
  managedSecretReference:
    secretName: infisical-auth-secret
    secretNamespace: infisical-operator-system
  mapping:
    - secretKey: userID
      infisicalKey: CEPH_CEPHFS_USER_ID
    - secretKey: userKey
      infisicalKey: CEPH_CEPHFS_USER_KEY  
    - secretKey: adminID
      infisicalKey: CEPH_ADMIN_ID
    - secretKey: adminKey
      infisicalKey: CEPH_ADMIN_KEY
