# Infisical-managed secrets for Ceph CSI drivers
# These secrets contain user keys and credentials for accessing the external Ceph cluster

apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ceph-csi-rbd-secret
  namespace: ceph-csi-rbd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/ceph"
        recursive: false
  managedSecretReference:
    secretName: csi-rbd-secret
    secretNamespace: ceph-csi-rbd
    secretType: Opaque
    creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ceph-csi-cephfs-secret
  namespace: ceph-csi-cephfs
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/ceph"
        recursive: false
  managedSecretReference:
    secretName: csi-cephfs-secret
    secretNamespace: ceph-csi-cephfs
    secretType: Opaque
    creationPolicy: Owner
