# Ceph CSI Secrets managed by Infisical
# 
# PREREQUISITE: Run scripts/setup-infisical-auth.ps1 first to create auth credentials
# This will create Kubernetes secrets from Infisical secret store
#
# REQUIRED INFISICAL SECRETS (in /ceph path):
# For CSI (existing):
# - userID: <client.csi-rbd-node>
# - userKey: <client.csi-rbd-node key>
# - adminID: <client.admin>
# - adminKey: <client.admin key>
# - csi-cephfs-node: <client.csi-cephfs-node key>
# - csi-cephfs-provisioner: <client.csi-cephfs-provisioner key>
# 
# For Rook External Cluster (new, required for NFS-Ganesha):
# - admin-secret: <client.admin key>
# - mon-secret: <full mon keyring content>
# - bootstrap-osd-secret: <client.bootstrap-osd key>
# - bootstrap-mds-secret: <client.bootstrap-mds key>
# - bootstrap-rbd-secret: <client.bootstrap-rbd key>
# - bootstrap-rgw-secret: <client.bootstrap-rgw key>
# - csi-rbd-node-secret: <client.csi-rbd-node key>
# - csi-cephfs-node-secret: <client.csi-cephfs-node key>
# - csi-rbd-provisioner-secret: <client.csi-rbd-provisioner key>
# - csi-cephfs-provisioner-secret: <client.csi-cephfs-provisioner key>

# Create required namespaces first
---
apiVersion: v1
kind: Namespace
metadata:
  name: ceph-csi-rbd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    name: ceph-csi-rbd
---
apiVersion: v1
kind: Namespace
metadata:
  name: ceph-csi-cephfs
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    name: ceph-csi-cephfs

---
# Infisical Secret for RBD authentication
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ceph-rbd-infisical-secret
  namespace: ceph-csi-rbd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretsPath: "/ceph"
  projectId: "f492c339-2822-40bd-84cb-6f32326a3a38"
  envSlug: "prod"
  secretType: Opaque
  resyncInterval: 60
  managedSecretReference:
    secretName: csi-rbd-secret
    secretNamespace: ceph-csi-rbd
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      secretsScope:
        projectId: "f492c339-2822-40bd-84cb-6f32326a3a38"
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"        
        secretsPath: "/ceph"
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
---
# Infisical Secret for CephFS authentication
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ceph-cephfs-infisical-secret
  namespace: ceph-csi-cephfs
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretsPath: "/ceph"
  projectId: "f492c339-2822-40bd-84cb-6f32326a3a38"  # Replace with your Infisical project ID
  envSlug: "prod"
  secretType: Opaque
  resyncInterval: 60
  managedSecretReference:
    secretName: csi-cephfs-secret
    secretNamespace: ceph-csi-cephfs
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      secretsScope:
        projectId: "f492c339-2822-40bd-84cb-6f32326a3a38"
        projectSlug: "ombra-mi-wk"  # Replace with your actual project slug
        envSlug: "prod"
        secretsPath: "/ceph"
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system

---
# Namespace for Rook Ceph
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    name: rook-ceph
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged

---
# Infisical Secret for Rook external cluster access
# This creates the rook-ceph-mon secret that contains all bootstrap keys
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: rook-ceph-external-secret
  namespace: rook-ceph
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretsPath: "/ceph"
  projectId: "f492c339-2822-40bd-84cb-6f32326a3a38"
  envSlug: "prod"
  secretType: Opaque
  resyncInterval: 60
  managedSecretReference:
    secretName: rook-ceph-mon
    secretNamespace: rook-ceph
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      secretsScope:
        projectId: "f492c339-2822-40bd-84cb-6f32326a3a38"
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/ceph"
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
