# Ceph CSI Secrets managed by Infisical
# 
# PREREQUISITE: Run scripts/setup-infisical-auth.ps1 first to create auth credentials
# This will create Kubernetes secrets from Infisical secret store

# Infisical Secret for RBD authentication
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ceph-rbd-infisical-secret
  namespace: ceph-csi-rbd
spec:
  secretsPath: "/ceph"
  projectId: "f492c339-2822-40bd-84cb-6f32326a3a38"
  envSlug: "prod"
  secretType: Opaque
  resyncInterval: 60
  managedSecretReference:
    secretName: csi-rbd-secret
    secretNamespace: ceph-csi-rbd
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      secretsScope:
        projectId: "f492c339-2822-40bd-84cb-6f32326a3a38"
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"        
        secretsPath: "/ceph"
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
---
# Infisical Secret for CephFS authentication
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ceph-cephfs-infisical-secret
  namespace: ceph-csi-cephfs
spec:
  secretsPath: "/ceph"
  projectId: "f492c339-2822-40bd-84cb-6f32326a3a38"  # Replace with your Infisical project ID
  envSlug: "prod"
  secretType: Opaque
  resyncInterval: 60
  managedSecretReference:
    secretName: csi-cephfs-secret
    secretNamespace: ceph-csi-cephfs
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      secretsScope:
        projectId: "f492c339-2822-40bd-84cb-6f32326a3a38"
        projectSlug: "ombra-mi-wk"  # Replace with your actual project slug
        envSlug: "prod"
        secretsPath: "/ceph"
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
