apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Deploy Ceph secrets (via Infisical) first
  - ceph-secrets.yaml
  # Then deploy CSI drivers
  - ceph-csi.yaml
  # Create simple shared media storage - THIS IS THE RECOMMENDED APPROACH
  - simple-shared-media.yaml

# Alternative approaches (commented out):
# - shared-media-pvc.yaml      # More complex version with multiple features
# - namespace-pvcs.yaml        # Cross-namespace PVC references (may not work reliably)

# Include documentation
configMapGenerator:
- name: shared-media-docs
  files:
  - README-shared-media.md
  - EXAMPLES-application-updates.md
  - USAGE-GUIDE.md
