apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Set the default namespace for resources
namespace: media-storage

resources:
  # Deploy Ceph secrets (via Infisical) first
  - ceph-secrets.yaml
  # Then deploy CSI drivers
  - ceph-csi.yaml
  # Create simple shared media storage - THIS IS THE RECOMMENDED APPROACH
  - simple-shared-media.yaml
  # Create PVCs in each application namespace
  - namespace-pvcs.yaml

# Note: Documentation is included in the repository but not deployed as ConfigMaps
# to avoid namespace conflicts. Reference the markdown files directly.
