apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Deploy Ceph secrets (via Infisical) first
  - ceph-secrets.yaml
  # Then deploy CSI drivers
  - ceph-csi.yaml
  # Create simple shared media storage - THIS IS THE RECOMMENDED APPROACH
  - cross-namespace-shared-storage.yaml

# Note: No default namespace set to avoid conflicts since resources go to different namespaces
