apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Deploy Ceph secrets (via Infisical) first
  - ceph-secrets.yaml
  # Then deploy CSI drivers
  - ceph-csi.yaml
  # Create shared media storage structure
  - shared-media-pvc.yaml
  # Create namespace-specific PVC references
  - namespace-pvcs.yaml

# Include documentation
configMapGenerator:
- name: shared-media-docs
  files:
  - README-shared-media.md
  - EXAMPLES-application-updates.md
