apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Deploy Ceph secrets (via Infisical) first
  - ceph-secrets.yaml
  # Then deploy CSI drivers
  - ceph-csi.yaml
  # Deploy NFS-Ganesha in Kubernetes (depends on Ceph CSI)
  - nfs-ganesha-k8s.yaml
  # Create media namespaces and verification jobs
  - nfs-shared-storage.yaml

# Note: No default namespace set to avoid conflicts since resources go to different namespaces
# Applications will mount NFS directly - no shared PVCs needed
