apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ceph-secrets.yaml
  - ceph-csi.yaml

commonLabels:
  app.kubernetes.io/part-of: storage
  app.kubernetes.io/managed-by: argocd
