# Namespace-specific PVCs that all point to the same CephFS storage
# Note: Namespaces are created by individual application deployments
# This just creates the PVCs that applications will reference

# Plex namespace PVC - for media library access
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media-data
  namespace: plex
  labels:
    app: shared-media
    component: storage
    access-pattern: media-only
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-cephfs
  resources:
    requests:
      storage: 2Ti

# Arr namespace PVC - for full media management access
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media-data
  namespace: arr
  labels:
    app: shared-media
    component: storage
    access-pattern: full-access
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-cephfs
  resources:
    requests:
      storage: 2Ti

# Downloads namespace PVC - for download management
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media-data
  namespace: downloads
  labels:
    app: shared-media
    component: storage
    access-pattern: downloads-access
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-cephfs
  resources:
    requests:
      storage: 2Ti
