# Namespace-specific PVCs that all point to the same CephFS storage
# This is the cleanest approach for shared storage across namespaces

# Plex namespace PVC - for media library access
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media-data
  namespace: plex
  labels:
    app: shared-media
    component: storage
    access-pattern: media-only
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-cephfs
  resources:
    requests:
      storage: 2Ti

# Arr namespace PVC - for full media management access
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media-data
  namespace: arr
  labels:
    app: shared-media
    component: storage
    access-pattern: full-access
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-cephfs
  resources:
    requests:
      storage: 2Ti

# Downloads namespace PVC - for download management
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media-data
  namespace: downloads
  labels:
    app: shared-media
    component: storage
    access-pattern: downloads-access
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-cephfs
  resources:
    requests:
      storage: 2Ti
