---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: filebeat
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    helm:
      releaseName: filebeat
      values: |
        # Filebeat configuration for log shipping to Wazuh
        daemonset:
          enabled: true
          
          # Override the default secret mounts to use the correct Elasticsearch secret names
          secretMounts:
            - name: wazuh-cluster-master-certs
              secretName: wazuh-cluster-master-certs
              path: /usr/share/filebeat/certs/
          
          # Override environment variables to use the correct secret names
          extraEnvs:
            - name: "ELASTICSEARCH_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: wazuh-cluster-master-credentials
                  key: username
            - name: "ELASTICSEARCH_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: wazuh-cluster-master-credentials
                  key: password
          
        # Resource configuration
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        # Filebeat configuration
        filebeatConfig:
          filebeat.yml: |
            filebeat.inputs:
            - type: container
              paths:
                - /var/log/containers/*.log
              processors:
                - add_kubernetes_metadata:
                    host: ${NODE_NAME}
                    matchers:
                    - logs_path:
                        logs_path: "/var/log/containers/"
                - decode_json_fields:
                    fields: ["message"]
                    max_depth: 1
                    target: ""
                    overwrite_keys: true
            
            processors:
              - add_host_metadata:
                  when.not.contains.tags: forwarded
              - add_cloud_metadata: ~
              - add_docker_metadata: ~
              - add_kubernetes_metadata: ~
            
            output.elasticsearch:
              hosts: ["https://elasticsearch-master:9200"]
              username: "elastic"
              password: "wazuh123"
              ssl.verification_mode: none
              template.name: "wazuh"
              template.pattern: "wazuh-alerts-*"
              template.settings:
                index.number_of_shards: 1
                index.number_of_replicas: 0
                index.refresh_interval: 5s
            
            setup.template.name: "wazuh"
            setup.template.pattern: "wazuh-alerts-*"
            setup.ilm.enabled: false
            
            logging.level: info
            logging.to_files: true
            logging.files:
              path: /var/log/filebeat
              name: filebeat.log
              keepfiles: 7
              permissions: 0644
        
        # Security context
        securityContext:
          runAsUser: 0
          privileged: true
        
        # Tolerations to run on all nodes
        tolerations:
          - effect: NoSchedule
            operator: Exists
          - effect: NoExecute
            operator: Exists
        
        # ServiceMonitor for monitoring Filebeat itself
        serviceMonitor:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: wazuh-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
