apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

resources:
  - ./wazuh-agent-serviceaccount.yaml
  - ./wazuh-agent-clusterrole.yaml
  - ./wazuh-agent-clusterrolebinding.yaml
  - ./wazuh-agent-configmap.yaml
  - ./wazuh-agent-daemonset.yaml
