apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  labels:
    app: wazuh-agent
    app.kubernetes.io/name: wazuh-agent
    app.kubernetes.io/part-of: wazuh
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wazuh-agent
        app.kubernetes.io/name: wazuh-agent
        app.kubernetes.io/part-of: wazuh
    spec:
      serviceAccountName: wazuh-agent
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      priorityClassName: system-node-critical
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      initContainers:
        - name: prepare-config
          image: wazuh/wazuh-agent:4.13.0-rc4
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - sh
            - -c
            - |
              set -euo pipefail
              echo "[init] Staging writable ossec.conf";
              cp -a /var/ossec/etc/* /ossec-etc/ 2>/dev/null || true
              if [ -f /config/ossec.conf ]; then
                cp /config/ossec.conf /ossec-etc/ossec.conf
              fi
              sed -i "s|%NODE_NAME%|${NODE_NAME}|g" /ossec-etc/ossec.conf || true
              echo "[init] Completed config staging";
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: ossec-etc
              mountPath: /ossec-etc
      containers:
        - name: agent
          image: wazuh/wazuh-agent:4.13.0-rc4
          imagePullPolicy: IfNotPresent
          env:
            - name: WAZUH_MANAGER
              value: wazuh
            - name: WAZUH_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WAZUH_REGISTRATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-authd-pass
                  key: authd.pass
            - name: AUTHD_SERVER
              value: wazuh
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WAZUH_AGENT_GROUP
              value: k8s-talos-nodes
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: containers
              mountPath: /var/log/containers
              readOnly: true
            - name: pods
              mountPath: /var/log/pods
              readOnly: true
            - name: kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: ossec-etc
              mountPath: /var/ossec/etc
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
      terminationGracePeriodSeconds: 30
      hostNetwork: false
      dnsPolicy: ClusterFirst
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/log/containers
        - name: pods
          hostPath:
            path: /var/log/pods
        - name: kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: config
          configMap:
            name: wazuh-agent-config
        - name: ossec-etc
          emptyDir: {}
