apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-agent-config
  namespace: wazuh
  labels:
    app.kubernetes.io/name: wazuh-agent
    app.kubernetes.io/part-of: wazuh
data:
  # Minimal Wazuh agent ossec.conf fragment - will be wrapped or used directly by init script.
  ossec.conf: |
    <ossec_config>
      <client>
        <server>
          <address>wazuh</address>
          <port>1514</port>
          <protocol>tcp</protocol>
        </server>
        <config-profile>k8s-node</config-profile>
      </client>
      <logging>
        <log_format>json</log_format>
      </logging>
      <localfile>
        <location>/var/log/containers</location>
        <log_format>json</log_format>
        <recursive>yes</recursive>
      </localfile>
      <localfile>
        <location>/var/log/kube-apiserver.log</location>
        <log_format>syslog</log_format>
        <ignore_binaries>no</ignore_binaries>
      </localfile>
    </ossec_config>
