apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  labels:
    app: wazuh-agent
    app.kubernetes.io/name: wazuh-agent
    app.kubernetes.io/part-of: wazuh
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wazuh-agent
        app.kubernetes.io/name: wazuh-agent
        app.kubernetes.io/part-of: wazuh
    spec:
      serviceAccountName: wazuh-agent
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      priorityClassName: system-node-critical
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: agent
          image: wazuh/wazuh-agent:4.13.0-rc4
          imagePullPolicy: IfNotPresent
          env:
            - name: WAZUH_MANAGER
              value: wazuh
            # Let the image defaults handle port/protocol unless override needed.
            - name: WAZUH_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WAZUH_REGISTRATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-authd-pass
                  key: authd.pass
            - name: AUTHD_SERVER
              value: wazuh
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WAZUH_AGENT_GROUP
              value: k8s-talos-nodes
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: containers
              mountPath: /var/log/containers
              readOnly: true
            - name: pods
              mountPath: /var/log/pods
              readOnly: true
            - name: kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: config
              # Override default agent configuration
              mountPath: /var/ossec/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
      terminationGracePeriodSeconds: 30
      hostNetwork: false
      dnsPolicy: ClusterFirst
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/log/containers
        - name: pods
          hostPath:
            path: /var/log/pods
        - name: kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: config
          configMap:
            name: wazuh-agent-config
