apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.19.1
    helm:
      values: |
        # Install CRDs
        installCRDs: true
        
        # Global configuration
        global:
          leaderElection:
            namespace: cert-manager

        # Webhook configuration
        webhook:
          replicaCount: 1

        # CA Injector configuration
        cainjector:
          replicaCount: 1

        # Configure cert-manager to use Cloudflare DNS for DNS-01 challenge verification
        # Using --dns01-recursive-nameservers-only forces cert-manager to use ONLY the specified nameserver
        # Without this flag, cert-manager may fall back to system DNS, causing verification inconsistencies
        # Cloudflare DNS (1.1.1.1) matches where the TXT records are stored
        extraArgs:
          - --dns01-recursive-nameservers-only
          - --dns01-recursive-nameservers=1.1.1.1:53

        # Prometheus monitoring - disabled until Prometheus Operator is installed
        prometheus:
          enabled: false
          servicemonitor:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default  
  source:
    repoURL: https://github.com/mhwilkes/ombra-labops.git
    targetRevision: HEAD
    path: gitops/apps/infrastructure/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
