apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: 1.14.4    
    helm:
      values: |
        # Cilium configuration for Ombra cluster on Talos Linux
        k8sServiceHost: 192.168.55.220  # Your cluster VIP
        k8sServicePort: 6443
        
        # Talos Linux specific configuration
        securityContext:
          privileged: true
        
        # Disable features that don't work well with Talos
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup
        
        # Configure for Talos paths
        bpf:
          root: /sys/fs/bpf
          masquerade: true
        
        # Enable required capabilities for Talos
        initContainer:
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
        
        # Enable Hubble for observability
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
            service:
              type: ClusterIP
        
        # Disable ingress controller (we'll use NGINX instead)
        ingressController:
          enabled: false
        
        # Enable L2 announcements for LoadBalancer services
        l2announcements:
          enabled: true
        
        # Operator configuration
        operator:
          replicas: 1
        
        # IPAM configuration
        ipam:
          mode: kubernetes
        
        # Enable native routing for Talos
        routingMode: native
        autoDirectNodeRoutes: true
        tunnel: disabled
        
        # Kube-proxy replacement (compatible with Talos)
        kubeProxyReplacement: strict
        k8sRequireIPv4PodCIDR: true
        
        # Talos-compatible sysctls
        sysctlChanges:        # Talos-compatible sysctls
        sysctlChanges: []
        
        # Security policies
        policyEnforcementMode: default
        
        # Disable clean-cilium-state init container (causes issues on Talos)
        cleanBpfState: false
        cleanState: false
        
        # Configure resources
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
