apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: 1.14.4
    helm:
      values: |
        # Cilium configuration for Ombra cluster
        k8sServiceHost: 192.168.55.100  # Update with your API server IP
        k8sServicePort: 6443
        
        # Enable Hubble for observability
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
            service:
              type: ClusterIP
        
        # Enable ingress controller
        ingressController:
          enabled: true
          service:
            type: LoadBalancer
            loadBalancerIP: 192.168.55.200  # Update with your desired IP
        
        # Enable L2 announcements for LoadBalancer services
        l2announcements:
          enabled: true
        
        # Enable local redirect policy
        localRedirectPolicy: true
        
        # Operator configuration
        operator:
          replicas: 1
        
        # IPAM configuration
        ipam:
          mode: kubernetes
        
        # Enable native routing
        routingMode: native
        autoDirectNodeRoutes: true
        
        # Kube-proxy replacement
        kubeProxyReplacement: strict
        
        # Enable BPF masquerading
        bpf:
          masquerade: true
        
        # Security policies
        policyEnforcementMode: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
