apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.14.1
    helm:
      values: |
        # Controller configuration
        controller:
          # Resources
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
          
          # Security context
          securityContext:
            runAsUser: 65534
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          # Service Monitor for Prometheus - disabled until Prometheus Operator is installed
        serviceMonitor:
          create: false
        
        # Network policy
        networkPolicy:
          create: false
        
        # Pod security policy
        podSecurityPolicy:
          create: false
        
        # RBAC
        rbac:
          create: true
          pspEnabled: false
        
        # Service account
        serviceAccount:
          create: true
          name: sealed-secrets-controller
        
        # Deployment strategy
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        
        # Pod disruption budget
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
