apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: talosconfig-workers
spec:
  template:
    spec:
      generateType: worker
      talosVersion: v1.33.0
      configPatches:
          - op: replace
            path: /machine/install
            value:
              disk: /dev/sda
          - op: add
            path: /machine/kubelet/extraArgs
            value:
              cloud-provider: external
          - op: add
            path: /machine/time
            value:
              disabled: false
              servers:
                - time.cloudflare.com
          - op: add
            path: /machine/network/nameservers
            value:
              - 192.168.0.20
              - 8.8.8.8
              - 1.1.1.1
          - op: add
            path: /machine/kubelet/extraArgs
            value:
              cloud-provider: external
          - op: add
            path: /machine/kubelet/extraArgs/rotate-server-certificates
            value: "true"