# Bazarr Secrets managed by Infisical
# 
# PREREQUISITE: Add any API keys to Infisical under /bazarr path in the ombra-mi-wk project

apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: bazarr-infisical-secret
  namespace: media
spec:
  resyncInterval: 60
  managedSecretReference:
    secretName: bazarr-secrets
    secretNamespace: media
    secretType: Opaque
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/bazarr"
