apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maintainerr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # Library maintenance after Plex
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.1.2
    helm:
      values: |          
        controllers:
          maintainerr:
            pod:
              securityContext:
                runAsUser: 2000
                runAsGroup: 2000
                runAsNonRoot: true
                fsGroup: 2000
                fsGroupChangePolicy: "Always"
            containers:
              app:                
                image:
                  repository: ghcr.io/jorenn92/maintainerr
                  tag: 2.18.1                
                env:
                  TZ: America/New_York
                probes:
                  liveness:
                    enabled: true
                  readiness:
                    enabled: true
                  startup:
                    enabled: true
                    spec:
                      failureThreshold: 30
                      periodSeconds: 5
                resources:
                  requests:
                    cpu: 10m
                    memory: 250Mi
                  limits:
                    memory: 1Gi
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL
        service:
          app:
            controller: maintainerr
            ports:
              http:
                port: 6246
        ingress:
          app:
            enabled: true
            className: nginx            
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: maintainerr.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: maintainerr-tls
                hosts:
                  - maintainerr.michaelwilkes.dev        
        persistence:
          data:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-configs
            size: 1Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /opt/data
          tmp:
            enabled: true
            type: emptyDir
            globalMounts:
              - path: /tmp
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
