# Plex Secrets managed by Infisical
# 
# This manages sensitive Plex configuration like claim tokens
# The CLAIM_TOKEN secret in Infisical will be mapped to PLEX_CLAIM env var

apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: plex-infisical-secret
  namespace: media
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  resyncInterval: 60
  managedSecretReference:
    secretName: plex-secrets
    secretNamespace: media
    secretType: Opaque
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/plex"
  secretsMapping:
    - secretKey: "PLEX_CLAIM"
      infisicalKey: "PLEX_CLAIM"
