apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Media server after content management
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      values: |
        controllers:
          plex:
            pod:
              securityContext:
                runAsUser: 2000
                runAsGroup: 2000
                runAsNonRoot: true
                fsGroup: 2000
                fsGroupChangePolicy: "Always"
            containers:
              app:
                image:
                  repository: ghcr.io/home-operations/plex
                  tag: 1.41.8.9834                  
                env:
                  TZ: America/New_York
                  PLEX_UID: 2000
                  PLEX_GID: 2000
                  TRANSCODE_PATH: /transcode
                  ADVERTISE_IP: "http://192.168.55.210:32400/"                  
                  PLEX_CLAIM:
                    valueFrom:
                      secretKeyRef:
                        name: plex-secrets
                        key: PLEX_CLAIM
                resources:
                  requests:
                    cpu: 100m
                    memory: 2Gi
                  limits:
                    cpu: 4000m
                    memory: 8Gi
        service:
          app:
            controller: plex
            type: LoadBalancer
            loadBalancerIP: 192.168.55.210
            ports:
              http:
                port: 32400        
        ingress:
          app:
            enabled: true
            className: nginx            
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: plex.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: plex-tls
                hosts:
                  - plex.michaelwilkes.dev        
        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-configs
            size: 10Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /config                
          media:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: media-shared-storage
            globalMounts:
              - path: /data/media  # TRASHGuides: Plex only needs access to media library
                subPath: "media"   # Mount only the media subdirectory
                readOnly: true     # Plex should only read from media library
          transcode:
            enabled: true
            type: emptyDir
            sizeLimit: 10Gi
            globalMounts:
              - path: /transcode
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
