# Prowlarr Secrets managed by Infisical
# 
# PREREQUISITE: Add the API key to Infisical under /prowlarr path in the ombra-mi-wk project

apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: prowlarr-infisical-secret
  namespace: media
spec:
  resyncInterval: 60
  managedSecretReference:
    secretName: prowlarr-secret
    secretNamespace: media
    secretType: Opaque
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/prowlarr"
