apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Download clients foundation
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.1.2
    helm:
      values: |          
        controllers:
          qbittorrent:
            type: deployment
            strategy: Recreate            
            pod:
              securityContext:
                runAsUser: 1000  # Standard media user ID
                runAsGroup: 1000  # Standard media group ID
                runAsNonRoot: true
                fsGroup: 1000
                fsGroupChangePolicy: "Always"
            containers:
              app:
                image:
                  repository: ghcr.io/home-operations/qbittorrent
                  tag: 5.1.2                
                env:
                  TZ: America/New_York
                  QBITTORRENT__PORT: 8080
                  QBITTORRENT__BT_PORT: 6881
                  QBT_Application__MemoryWorkingSetLimit: 8000
                probes:
                  liveness:
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /
                        port: 8080
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness:
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /
                        port: 8080
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                resources:
                  requests:
                    cpu: 10m
                    memory: 250Mi
                  limits:
                    memory: 8Gi
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL
        service:
          app:
            controller: qbittorrent
            type: LoadBalancer
            loadBalancerIP: 192.168.55.211
            ports:
              http:
                port: 8080
              bittorrent:
                port: 6881
                protocol: TCP
                targetPort: 6881
        ingress:
          app:
            enabled: true
            className: nginx            
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: qbittorrent.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: qbittorrent-tls
                hosts:
                  - qbittorrent.michaelwilkes.dev
        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-configs
            size: 1Gi
            accessMode: ReadWriteOnce            
            globalMounts:
              - path: /config            
          data:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: media-shared-storage
            globalMounts:
              - path: /data
                subPath: ""  # Mount the entire shared volume for Trash Guides structure
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
