apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Content management after indexers
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.1.2
    helm:
      values: |          
        controllers:
          radarr:
            type: deployment
            strategy: Recreate            
            pod:
              securityContext:
                runAsUser: 1000  # Standard media user ID
                runAsGroup: 1000  # Standard media group ID
                runAsNonRoot: true
                fsGroup: 1000
                fsGroupChangePolicy: OnRootMismatch
            containers:
              app:                
                image:
                  repository: ghcr.io/home-operations/radarr
                  tag: 6.1.0.10293                
                env:
                  TZ: America/New_York
                  RADARR__APP__INSTANCENAME: Radarr
                  RADARR__AUTH__METHOD: External
                  RADARR__LOG__DBENABLED: "False"
                  RADARR__LOG__LEVEL: info
                  RADARR__SERVER__PORT: &port 7878
                  RADARR__UPDATE__BRANCH: develop
                envFrom:
                  - secretRef:
                      name: radarr-secrets
                probes:
                  liveness: &probes
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /ping
                        port: *port
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness: *probes
                resources:
                  requests:
                    cpu: 10m
                    memory: 250Mi
                  limits:
                    memory: 2Gi
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL        
        service:
          app:
            controller: radarr
            ports:
              http:
                port: 7878
        ingress:
          app:
            enabled: true
            className: nginx            
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: radarr.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: radarr-tls
                hosts:
                  - radarr.michaelwilkes.dev
        persistence:
          config:
            type: persistentVolumeClaim
            storageClass: ceph-configs
            size: 1Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /config              
          data:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: media-shared-storage
            globalMounts:
              - path: /data
                subPath: ""  # Mount the entire shared volume for Trash Guides structure
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
