# Recyclarr Secrets managed by Infisical
# 
# PREREQUISITE: Add the API keys to Infisical under /recyclarr path in the ombra-mi-wk project
# Required secrets:
# - RADARR_API_KEY: Get from Radarr -> Settings -> General -> Security -> API Key
# - SONARR_API_KEY: Get from Sonarr -> Settings -> General -> Security -> API Key

apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: recyclarr-infisical-secret
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  resyncInterval: 60
  managedSecretReference:
    secretName: recyclarr-secrets
    secretNamespace: media
    secretType: Opaque
    creationPolicy: "Owner"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: "ombra-mi-wk"
        envSlug: "prod"
        secretsPath: "/recyclarr"
