apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recyclarr
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      values: |
        controllers:
          recyclarr:
            type: cronjob
            cronjob:
              schedule: "0 */6 * * *"  # Run every 6 hours
              successfulJobsHistory: 1
              failedJobsHistory: 1
            
            containers:
              app:
                image:
                  repository: ghcr.io/recyclarr/recyclarr
                  tag: 7.2.4
                env:
                  TZ: America/New_York
                args:
                  - sync
                resources:
                  requests:
                    cpu: 10m
                    memory: 50Mi
                  limits:
                    memory: 200Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL
            
            pod:
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
                fsGroup: 1000
        
        service:
          app:
            controller: recyclarr
            enabled: false

        persistence:
          config:
            type: persistentVolumeClaim
            storageClass: ceph-configs
            size: 1Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /config
          
          tmp:
            type: emptyDir
            globalMounts:
              - path: /tmp

  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
