apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recyclarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # TRaSH Guides automation after *arr apps
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.1.2
    helm:
      values: |
        controllers:
          recyclarr:
            type: cronjob
            cronjob:
              schedule: "0 */6 * * *"  # Run every 6 hours
              timeZone: "America/New_York"
              successfulJobsHistory: 1
              failedJobsHistory: 3
              concurrencyPolicy: Forbid
            
            containers:
              app:
                image:
                  repository: ghcr.io/recyclarr/recyclarr
                  tag: 7.4.1
                env:
                  TZ: America/New_York
                  RECYCLARR_CONFIG_DIR: /config
                  RADARR_API_KEY:
                    valueFrom:
                      secretKeyRef:
                        name: recyclarr-secrets
                        key: RADARR_API_KEY
                  SONARR_API_KEY:
                    valueFrom:
                      secretKeyRef:
                        name: recyclarr-secrets
                        key: SONARR_API_KEY
                args:
                  - sync
                resources:
                  requests:
                    cpu: 10m
                    memory: 50Mi
                  limits:
                    cpu: 100m
                    memory: 200Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL
            
            pod:
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
                fsGroup: 1000
        
        service:
          app:
            controller: recyclarr
            enabled: false

        configMaps:
          config:
            enabled: true
            data:
              recyclarr.yml: |
                ###################################################################################################
                # Recyclarr Configuration Template: Remux + WEB 2160p                                             #
                # Updated: 2025-05-04                                                                             #
                # Documentation: https://recyclarr.dev                                                            #
                # Note: If you are using multiple profiles in a single instance, please read the following        #
                # documentation about file merging:                                                               #
                # https://recyclarr.dev/wiki/yaml/config-examples/#merge-single-instance                          #
                ###################################################################################################
                
                # Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/
                radarr:
                  remux-web-2160p:
                    base_url: http://radarr:7878
                    api_key: !env_var RADARR_API_KEY

                    include:
                      # Comment out any of the following includes to disable them
                      - template: radarr-quality-definition-movie
                      - template: radarr-quality-profile-remux-web-2160p
                      - template: radarr-custom-formats-remux-web-2160p

                    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
                    custom_formats:
                      - trash_ids:
                      # Audio - Enable Advanced Audio Formats for 2160p quality
                          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
                          - 2f22d89048b01681dde8afe203bf2e95 # DTS X
                          - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
                          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
                          - 3cafb66171b47f226146a0770576870f # TrueHD
                          - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
                          - a570d4a0e56a2874b64e5bfa55202a9b # FLAC
                          - e7c2fcae07cbada050a0af3357491d7b # PCM
                          - 8e109e50e0a0b83b5098b056e13bf6db # DTS-HD HRA
                          - 185f1dd7264c4562b9022d963ac37424 # DD+
                          - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
                          - 1c1a4c5e823891c75bc50380a6866f73 # DTS
                          - 240770601cc226190c367ef59aba7463 # AAC
                          - c2998bd0d90ed5621d8df281e839436e # DD
                        assign_scores_to:
                          - name: Remux + WEB 2160p

                      # Movie Versions - Enable preferred movie versions
                      - trash_ids:
                          - 0f12c086e289cf966fa5948eac571f44 # Hybrid
                          - 570bc9ebecd92723d2d21500f4be314c # Remaster
                          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
                          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
                          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
                          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
                          - 957d0f44b592285f26449575e8b1167e # Special Edition
                          - eecf3a857724171f968a66cb5719e152 # IMAX
                          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
                        assign_scores_to:
                          - name: Remux + WEB 2160p

                      # Optional - Additional quality controls
                      - trash_ids:
                          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
                          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
                          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
                          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
                          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
                          - f537cf427b64c38c8e36298f657e4828 # Scene
                        assign_scores_to:
                          - name: Remux + WEB 2160p

                      # x265 (HD) - Disabled to prefer x264 for better compatibility
                      - trash_ids:
                          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
                        assign_scores_to:
                          - name: Remux + WEB 2160p
                            score: -10000
                      
                      - trash_ids:
                          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
                        assign_scores_to:
                          - name: Remux + WEB 2160p

                      # HDR/DV Settings optimized for 2160p
                      - trash_ids:
                          # Comment out the next line if all devices support DV
                          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)

                          # HDR10+ Boost - Enabled for devices that support HDR10+
                          - b17886cb4158d9fea189859409975758 # HDR10Plus Boost
                          - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost
                        assign_scores_to:
                          - name: Remux + WEB 2160p

                      # SDR blocking for 2160p content - prefer HDR/DV variants
                      - trash_ids:
                          - 9c38ebb7384dada637be8899efa68e6f # SDR
                          # - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
                        assign_scores_to:
                          - name: Remux + WEB 2160p
                            score: -10000

                sonarr:
                  web-1080p:
                    base_url: http://sonarr:8989
                    api_key: !env_var SONARR_API_KEY
                    
                    include:
                      # Comment out any of the following includes to disable them
                      - template: sonarr-quality-definition-series
                      - template: sonarr-quality-profile-web-1080p
                      - template: sonarr-custom-formats-web-1080p

                    # Custom Formats for TV Shows
                    custom_formats:
                      # HQ Release Groups
                      - trash_ids:
                          - d6819cba26b1a6508138d25fb5e32293 # WEB Tier 01
                          - 72b09c2db9cf3c2570b6e7b2ae01736d # WEB Tier 02
                          - 2016d1676f5ee13a5b7257ff86ac9a93 # WEB Tier 03
                        assign_scores_to:
                          - name: WEB-1080p

                      # Unwanted (avoid these releases)
                      - trash_ids:
                          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
                          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
                          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title)  
                          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
                          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
                        assign_scores_to:
                          - name: WEB-1080p
                            score: -10000

                      # Miscellaneous - proper releases
                      - trash_ids:
                          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
                          - eb3d5cc0a2be0db205fb823640db6a3c # Repack v2
                          - 44e7c4de10ae50265753082e5dc76047 # Repack v3
                        assign_scores_to:
                          - name: WEB-1080p

                      # Streaming Services
                      - trash_ids:
                          - d660701077794679fd59e8bdf4ce3a29 # AMZN
                          - f67c9ca88f463a48346062e8ad07713f # ATVP
                          - 36b72f59f4ea20aad9316f475f2d9fbb # DCU
                          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
                          - 7a235133c87f7da4c8cccceca7e3c7a6 # HBO
                          - a880d6abc21e7c16884f3ae393f84179 # HMAX
                          - f6cce30f1733d5c8194222a7507909bb # HULU
                          - 81d1fbf600e2540cee87f3a23f9d3c1c # MAX
                          - d34870697c9db575f17700212167be23 # NF
                          - 1656adc6d7bb2c8cca6acfb6592db421 # PCOK
                          - c67a75ae4a1715f2bb4d492755ba4195 # PMTP
                          - ae58039e1319178e6be73caab5c42166 # SHO
                        assign_scores_to:
                          - name: WEB-1080p

                      # Scene Groups
                      - trash_ids:
                          - e6258996055b9fbab7e9cb2f75819294 # WEB Scene
                        assign_scores_to:
                          - name: WEB-1080p

                  # Sonarr V4 instance for 4K TV shows
                  web-2160p-v4:
                    base_url: http://sonarr:8989
                    api_key: !env_var SONARR_API_KEY
                    
                    include:
                      # Comment out any of the following includes to disable them
                      - template: sonarr-quality-definition-series
                      # Choose between the standard or alternative quality profile setup (choose one only)
                      - template: sonarr-v4-quality-profile-web-2160p
                      # - template: sonarr-v4-quality-profile-web-2160p-alternative
                      - template: sonarr-v4-custom-formats-web-2160p

                    # Custom Formats for 4K TV Shows: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
                    custom_formats:
                      # HDR Formats
                      - trash_ids:
                          # Comment out the next line if you and all of your users' setups are fully DV compatible
                          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)

                          # HDR10+ Boost - Enable if any of your devices DO support HDR10+
                          - 0dad0a507451acddd754fe6dc3a7f5e7 # HDR10+ Boost
                          - 385e9e8581d33133c3961bdcdeffb7b4 # DV HDR10+ Boost
                        assign_scores_to:
                          - name: WEB-2160p

                      # Optional quality controls
                      - trash_ids:
                          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
                          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
                          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
                          - 06d66ab109d4d2eddb2794d21526d140 # Retags
                          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
                        assign_scores_to:
                          - name: WEB-2160p
                          
                      # x265 handling - disabled for better compatibility
                      - trash_ids:
                          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
                        assign_scores_to:
                          - name: WEB-2160p
                            score: -10000
                      
                      - trash_ids:
                          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
                        assign_scores_to:
                          - name: WEB-2160p

                      # SDR blocking for 4K content - prefer HDR variants
                      - trash_ids:
                          - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
                          # - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
                        assign_scores_to:
                          - name: WEB-2160p
                            score: -10000

        persistence:
          config:
            type: configMap
            name: recyclarr-config
            globalMounts:
              - path: /config
                readOnly: true
          
          data:
            type: persistentVolumeClaim
            storageClass: ceph-configs
            size: 1Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /data
          
          tmp:
            type: emptyDir
            globalMounts:
              - path: /tmp

  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
