apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Download clients foundation
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1    
    helm:
      values: |          
        controllers:
          sabnzbd:
            pod:
              securityContext:
                runAsUser: 1000  # Standard media user ID
                runAsGroup: 1000  # Standard media group ID
                runAsNonRoot: true
                fsGroup: 1000
                fsGroupChangePolicy: "Always"
              # Node affinity to prefer worker nodes with more available resources
              affinity:
                nodeAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    preference:
                      matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: DoesNotExist
                # Anti-affinity to avoid scheduling with other heavy workloads
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 50
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values: ["plex", "qbittorrent"]
                      topologyKey: kubernetes.io/hostname
            containers:
              app:
                image:
                  repository: ghcr.io/home-operations/sabnzbd
                  tag: 4.5.1                
                env:
                  TZ: America/New_York
                  SABNZBD__APP__INSTANCENAME: SABnzbd
                  SABNZBD__SERVER__PORT: &port 8080
                  SABNZBD__LOG__LEVEL: info
                  SABNZBD__HOST_WHITELIST_ENTRIES: "sabnzbd.michaelwilkes.dev,localhost,127.0.0.1"
                  SABNZBD__MISC__LOCAL_RANGES: "127.0.0.1,::1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
                  SABNZBD__MISC__HTTPS_CERT: ""
                  SABNZBD__MISC__HTTPS_KEY: ""
                  SABNZBD__MISC__ENABLE_HTTPS: "0"
                  # Performance optimization settings
                  SABNZBD__MISC__MAX_ART_TRY: "10"
                  SABNZBD__MISC__MAX_ARTICLE_TRIES: "5" 
                  SABNZBD__MISC__MAX_DOWNLOAD_RATE: "0"  # Unlimited
                  SABNZBD__MISC__CACHE_LIMIT: "2048M"    # 2GB cache for high-speed downloads
                  SABNZBD__MISC__DIRECT_UNPACK: "1"      # Enable direct unpacking
                  SABNZBD__MISC__IGNORE_SAMPLES: "1"     # Skip sample files
                  SABNZBD__MISC__AUTO_BROWSER: "0"       # Disable auto browser
                envFrom:
                  - secretRef:
                      name: sabnzbd-secrets
                probes:
                  liveness: &probes
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /
                        port: *port
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness: *probes                resources:
                  requests:
                    cpu: 2000m      # Request 2 cores (50% of node)
                    memory: 4Gi     # Request 4GB (50% of node)
                  limits:
                    cpu: 3500m      # Allow up to 3.5 cores (87.5% of node)
                    memory: 7Gi     # Allow up to 7GB (87.5% of node)
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL
        service:
          app:
            controller: sabnzbd            
            ports:
              http:
                port: 8080
        ingress:
          app:
            enabled: true
            className: nginx            
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: sabnzbd.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: sabnzbd-tls
                hosts:
                  - sabnzbd.michaelwilkes.dev        
        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-configs
            size: 1Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /config              
          data:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: media-shared-storage
            globalMounts:
              - path: /data
                subPath: ""              
          tmp:
            enabled: true
            type: emptyDir
            sizeLimit: 20Gi  # Increased for high-speed downloads and extraction
            globalMounts:
              - path: /tmp

  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
