apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Download clients foundation
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      values: |          
      controllers:
          sabnzbd:
            pod:
              securityContext:
                runAsUser: 2000
                runAsGroup: 2000
                runAsNonRoot: true
                fsGroup: 2000
                fsGroupChangePolicy: "Always"
            containers:
              app:
                image:
                  repository: ghcr.io/home-operations/sabnzbd
                  tag: 4.5.1
                env:
                  TZ: America/New_York
                  SABNZBD__APP__INSTANCENAME: SABnzbd
                  SABNZBD__SERVER__PORT: &port 8080
                  SABNZBD__LOG__LEVEL: info
                  # Fix hostname verification
                  SABNZBD__HOST_WHITELIST_ENTRIES: "sabnzbd.michaelwilkes.dev,localhost,127.0.0.1"
                  SABNZBD__MISC__LOCAL_RANGES: "127.0.0.1,::1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
                envFrom:
                  - secretRef:
                      name: sabnzbd-secrets
                probes:
                  liveness: &probes
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /
                        port: *port
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness: *probes
                resources:
                  requests:
                    cpu: 10m
                    memory: 250Mi
                  limits:
                    memory: 8Gi
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL
        service:
          app:
            controller: sabnzbd            
            ports:
              http:
                port: 8080
        ingress:
          app:
            enabled: true
            className: nginx            
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: sabnzbd.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: sabnzbd-tls
                hosts:
                  - sabnzbd.michaelwilkes.dev
        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-configs
            size: 1Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /config              
          data:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: media-shared-storage
            globalMounts:
              - path: /data
                subPath: ""  # Mount the entire shared volume for Trash Guides structure

  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
