apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default  
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      values: |
        controllers:
          sonarr:
            pod:
              securityContext:
                runAsUser: 2000
                runAsGroup: 2000
                runAsNonRoot: true
                fsGroup: 2000
                fsGroupChangePolicy: "Always"
            containers:
              app:                
                image:
                  repository: ghcr.io/home-operations/sonarr
                  tag: 4.0.15.2940
                env:
                  TZ: America/New_York
                  SONARR__APP__INSTANCENAME: Sonarr
                  SONARR__AUTH__METHOD: External
                  SONARR__LOG__DBENABLED: "False"
                  SONARR__LOG__LEVEL: info
                  SONARR__SERVER__PORT: &port 8989
                  SONARR__UPDATE__BRANCH: develop
                envFrom:
                  - secretRef:
                      name: sonarr-secrets
                probes:
                  liveness: &probes
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /ping
                        port: *port
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness: *probes
                resources:
                  requests:
                    cpu: 10m
                    memory: 250Mi
                  limits:
                    memory: 2Gi                
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL
        service:
          app:
            controller: sonarr
            ports:
              http:
                port: 8989
        ingress:
          app:
            enabled: true
            className: nginx            
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: sonarr.michaelwilkes.dev
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: app
                      port: http
            tls:
              - secretName: sonarr-tls
                hosts:
                  - sonarr.michaelwilkes.dev        
        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            storageClass: ceph-rbd
            size: 1Gi
            accessMode: ReadWriteOnce
            globalMounts:
              - path: /config            
          shared-data:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: media-shared-storage
            globalMounts:
              - path: /data
                subPath: ""  # Mount the entire shared volume for Trash Guides structure
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
